import type { Cover, Category } from '@/types'

export const covers: Cover[] = [
  {
    id: 'car-1',
    title: 'Midnight Velocity',
    category: 'Cars',
    slug: 'midnight-velocity',
    description: 'A cinematic portrait of speed and night. Made for the artist who moves fast and says nothing.',
    imageFile: 'car-1-title.png',
    videoCount: 2,
    priceImage: 6,
    priceWithVideos: 11,
    sold: false,
    featured: true,
  },
  {
    id: 'car-2',
    title: 'Chrome Dreams',
    category: 'Cars',
    slug: 'chrome-dreams',
    description: 'Polished metal meets ambient light. A cover that speaks to ambition without saying a word.',
    imageFile: 'car-2-title.png',
    videoCount: 2,
    priceImage: 6,
    priceWithVideos: 11,
    sold: false,
  },
  {
    id: 'car-3',
    title: 'Asphalt Soul',
    category: 'Cars',
    slug: 'asphalt-soul',
    description: 'Where the road ends and the music begins. Raw energy captured in a single frame.',
    imageFile: 'car-3-title.png',
    videoCount: 2,
    priceImage: 6,
    priceWithVideos: 10,
    sold: false,
  },
  {
    id: 'car-4',
    title: 'Neon Drive',
    category: 'Cars',
    slug: 'neon-drive',
    description: 'City lights, late nights, and the hum of an engine. Your soundtrack deserves this frame.',
    imageFile: 'car-4-title.png',
    videoCount: 1,
    priceImage: 5,
    priceWithVideos: 9,
    sold: false,
  },
  {
    id: 'car-5',
    title: 'Speed Ritual',
    category: 'Cars',
    slug: 'speed-ritual',
    description: "Some artists don't drive — they arrive. Built for the bold.",
    imageFile: 'car-5-title.png',
    videoCount: 1,
    priceImage: 5,
    priceWithVideos: 9,
    sold: false,
  },
  {
    id: 'cloud-1',
    title: 'Elevation',
    category: 'Abstract',
    slug: 'elevation',
    description: 'Above the noise, above the ordinary. A cover that breathes.',
    imageFile: 'cloud-title.png',
    videoCount: 1,
    priceImage: 4,
    priceWithVideos: 8,
    sold: false,
  },
  {
    id: 'female-1',
    title: 'Sovereign',
    category: 'Portraits',
    slug: 'sovereign',
    description: "Power isn't asked for — it's worn. A portrait that commands every room it enters.",
    imageFile: 'female-1-title.png',
    videoCount: 2,
    priceImage: 6,
    priceWithVideos: 10,
    sold: false,
    featured: true,
  },
  {
    id: 'female-2',
    title: 'Obsidian Queen',
    category: 'Portraits',
    slug: 'obsidian-queen',
    description: 'Dark energy, undeniable presence. For artists who define the room.',
    imageFile: 'female-2-title.png',
    videoCount: 1,
    priceImage: 5,
    priceWithVideos: 8,
    sold: false,
  },
  {
    id: 'female-look',
    title: 'The Gaze',
    category: 'Portraits',
    slug: 'the-gaze',
    description: 'One look is all it takes. Intimacy as an art form.',
    imageFile: 'female-look-title.png',
    videoCount: 1,
    priceImage: 4,
    priceWithVideos: 7,
    sold: false,
  },
  {
    id: 'flowers-1',
    title: 'Bloom Season',
    category: 'Nature',
    slug: 'bloom-season',
    description: 'The loudest things grow quietly. A cover for artists who bloom on their own terms.',
    imageFile: 'flowers-title.png',
    videoCount: 2,
    priceImage: 6,
    priceWithVideos: 12,
    sold: false,
    featured: true,
  },
  {
    id: 'flowers-2',
    title: 'Petal Theory',
    category: 'Nature',
    slug: 'petal-theory',
    description: 'Every layer reveals something new. Complexity dressed as simplicity.',
    imageFile: 'flowers-2-title.png',
    videoCount: 1,
    priceImage: 5,
    priceWithVideos: 9,
    sold: false,
  },
  {
    id: 'flowers-3',
    title: 'Sacred Garden',
    category: 'Nature',
    slug: 'sacred-garden',
    description: 'Where music grows between the silence. Alive and deliberate.',
    imageFile: 'flowers-3-title.png',
    videoCount: 1,
    priceImage: 4,
    priceWithVideos: 8,
    sold: false,
  },
  {
    id: 'mask-1',
    title: 'Phantom',
    category: 'Abstract',
    slug: 'phantom',
    description: 'The face behind the voice. Mystery as identity.',
    imageFile: 'mask-1-title.png',
    videoCount: 2,
    priceImage: 5,
    priceWithVideos: 10,
    sold: false,
  },
  {
    id: 'mask-2',
    title: 'Beneath the Surface',
    category: 'Abstract',
    slug: 'beneath-the-surface',
    description: 'What you see is never all there is. A cover for artists with layers.',
    imageFile: 'mask-2-title.png',
    videoCount: 1,
    priceImage: 4,
    priceWithVideos: 8,
    sold: false,
  },
  {
    id: 'mask-3',
    title: 'Anonymous',
    category: 'Abstract',
    slug: 'anonymous',
    description: 'When the music speaks louder than the name. Bold in its restraint.',
    imageFile: 'mask-3-title.png',
    videoCount: 1,
    priceImage: 3,
    priceWithVideos: 6,
    sold: false,
  },
  {
    id: 'mask-4',
    title: 'The Other Face',
    category: 'Abstract',
    slug: 'the-other-face',
    description: 'Everyone wears a different face on stage. This one is unforgettable.',
    imageFile: 'mask-4-title.png',
    videoCount: 1,
    priceImage: 4,
    priceWithVideos: 8,
    sold: false,
  },
  {
    id: 'mask-5',
    title: 'Hidden Frequency',
    category: 'Abstract',
    slug: 'hidden-frequency',
    description: 'The signal behind the noise. Made for the artist only few will understand.',
    imageFile: 'mask-5-title.png',
    videoCount: 2,
    priceImage: 6,
    priceWithVideos: 11,
    sold: false,
  },
  {
    id: 'moon-dance',
    title: 'Lunar Drift',
    category: 'Abstract',
    slug: 'lunar-drift',
    description: 'When the world sleeps, the real ones move. Unearthly, undeniable.',
    imageFile: 'moon-dance-title.png',
    videoCount: 2,
    priceImage: 5,
    priceWithVideos: 10,
    sold: false,
  },
]

export const categories: Category[] = ['All', 'Cars', 'Portraits', 'Nature', 'Abstract']

export function getCoverBySlug(slug: string): Cover | undefined {
  return covers.find((c) => c.slug === slug)
}

export function getCoverById(id: string): Cover | undefined {
  return covers.find((c) => c.id === id)
}

export function getFeaturedCovers(): Cover[] {
  return covers.filter((c) => c.featured && !c.sold)
}

export function getCoversByCategory(category: Category): Cover[] {
  if (category === 'All') return covers
  return covers.filter((c) => c.category === category)
}
